## Firewall config role task ##

---

# 1. Open all important ports on UFW #

- name: Open HTTP port
  command: ufw allow 80/tcp
  become: true

- name: Open HTTPS port
  command: ufw allow 443/tcp
  become: true

- name: Open SSH port
  command: ufw allow "{{ ssh_port }}/tcp"
  become: true

- name: Enable UFW with default deny (incoming)
  command: ufw --force enable
  become: true

##################################################################
