## Fail2ban role tasks #

---

# 1. Install fail2ban and config #

- name: Install Fail2Ban
  apt:
    name: fail2ban
  become: true

- name: Configure Fail2Ban jail for SSH
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Restart fail2ban

- name: Enable service fail2ban.service, and not touch the state
  ansible.builtin.service:
    name: fail2ban.service
    enabled: true
  become: true
  
- name: Start service fail2ban.service, if not started
  ansible.builtin.service:
    name: fail2ban.service
    state: started
  become: true
#################################################

