## Server Update and Upgrade role tasks ##

---

# 1. Server Update repositorys #

- name: Update Ubuntu packages
  become: true
  apt:
    update_cache: true

##################################################################

# 2. Server Upgrade packages #

- name: Upgrade packages
  apt:
    upgrade: true
  become: true

##################################################################

# 3. Execute bash.sh file #

- name: Execute the bash.sh file
  script: ../files/bash.sh
  become: true

##################################################################
